const actionTypes = {
    CATEGORIES_LIST_FETCH_REQUEST: 'CATEGORIES_LIST_FETCH_REQUEST',
    CATEGORIES_LIST_FETCH_FAILURE: 'CATEGORIES_LIST_FETCH_FAILURE',
    CATEGORIES_LIST_FETCH_SUCCESS: 'CATEGORIES_LIST_FETCH_SUCCESS',
    CATEGORIES_LIST_RESET: 'CATEGORIES_LIST_RESET',
    CATEGORY_FETCH_REQUEST: 'CATEGORY_FETCH_REQUEST',
    CATEGORY_FETCH_FAILURE: 'CATEGORY_FETCH_FAILURE',
    CATEGORY_NEXT_PAGE_SUCCESS: 'CATEGORY_NEXT_PAGE_SUCCESS',
    CATEGORY_RESET: 'CATEGORY_RESET'
};

module.exports = actionTypes;